// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBC-vFmF82NKu0GJuhc5ADfEjESBDGixpE',
    appId: '1:15794778256:web:dc874cc25168cfb9016815',
    messagingSenderId: '15794778256',
    projectId: 'open-authenticator-by-skyost',
    authDomain: 'open-authenticator-by-skyost.firebaseapp.com',
    storageBucket: 'open-authenticator-by-skyost.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYeNY6kvsvlcSeNV2S7bk4dy_Ci7MhKc4',
    appId: '1:15794778256:android:c50397a0acd377de016815',
    messagingSenderId: '15794778256',
    projectId: 'open-authenticator-by-skyost',
    storageBucket: 'open-authenticator-by-skyost.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb7r_Axip8PHMb09tC4ED-_BNJeuiBNn4',
    appId: '1:15794778256:ios:e1e80e1776b6fd54016815',
    messagingSenderId: '15794778256',
    projectId: 'open-authenticator-by-skyost',
    storageBucket: 'open-authenticator-by-skyost.appspot.com',
    iosBundleId: 'app.openauthenticator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb7r_Axip8PHMb09tC4ED-_BNJeuiBNn4',
    appId: '1:15794778256:ios:e1e80e1776b6fd54016815',
    messagingSenderId: '15794778256',
    projectId: 'open-authenticator-by-skyost',
    storageBucket: 'open-authenticator-by-skyost.appspot.com',
    iosBundleId: 'app.openauthenticator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBC-vFmF82NKu0GJuhc5ADfEjESBDGixpE',
    appId: '1:15794778256:web:a35b229079e64373016815',
    messagingSenderId: '15794778256',
    projectId: 'open-authenticator-by-skyost',
    authDomain: 'open-authenticator-by-skyost.firebaseapp.com',
    storageBucket: 'open-authenticator-by-skyost.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBJlU59mo11xiD8MC0UF-XfubwHFQYDPDU',
    authDomain: 'open-authenticator-by-skyost.firebaseapp.com',
    projectId: 'open-authenticator-by-skyost',
    storageBucket: 'open-authenticator-by-skyost.appspot.com',
    messagingSenderId: '15794778256',
    appId: '1:15794778256:web:c4456809f1a1242f016815',
  );
}
