name: open-authenticator
title: Open Authenticator
version: 2.0.1
summary: A cross-platform OTP app, free and open-source.
description: Secure your online accounts with a free, open-source and lovely-crafted app.
license: GPL-3.0-only
icon: snap/gui/icon.svg
website:
  - https://openauthenticator.app
donation:
  - https://github.com/openauthenticator-app/openauthenticator?tab=readme-ov-file#donate
source-code:
  - https://github.com/openauthenticator-app/openauthenticator
contact:
  - https://openauthenticator.app/contact/
issues:
  - https://github.com/openauthenticator-app/openauthenticator/issues/

base: core24
confinement: strict
grade: stable

platforms:
  amd64:
    build-on:
      - amd64
    build-for:
      - amd64
  arm64:
    build-on:
      - arm64
    build-for:
      - arm64

slots:
  open-authenticator-dbus:
    interface: dbus
    bus: session
    name: app.openauthenticator

apps:
  open-authenticator:
    command: open_authenticator
    extensions:
      - gnome
    plugs:
      - network
      - polkit
    slots:
      - open-authenticator-dbus
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/lib/jvm/default-java/lib/server:$LD_LIBRARY_PATH
      XDG_DATA_DIRS: $SNAP/usr/share:$XDG_DATA_DIRS

parts:
  open-authenticator:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    override-build: |
      flutter_dir="$CRAFT_PART_BUILD/flutter-distro"

      if [ ! -d "$flutter_dir" ]; then
        git clone --depth 1 -b stable https://github.com/flutter/flutter.git "$flutter_dir"
        rm -f "$flutter_dir/engine/src/.gn"
      fi

      export PATH="$flutter_dir/bin:$PATH"

      flutter precache --linux
      flutter pub get
      dart run open_authenticator:compile_svg
      dart run build_runner build --delete-conflicting-outputs
      dart run slang
      dart run open_authenticator:generate \
        --sentry-dsn="https://62d37f58cce344048c4ef701da3c949c@romantic-goat.pikapod.net/1" \
        --revenue-cat-public-key-windows-linux="rcb_wJJfvBJCRpmDQpLnyJZGSkKbGshZ" \
        --revenue-cat-offering-id="contributor_plan_v2" \
        --logo-dev-api-key="pk_LtANBAqSSKuTTIoVjJ6O-w"
      dart run open_authenticator:generate_polkit_policy
      flutter build linux --release --verbose --target lib/main.dart

      cp -r build/linux/*/release/bundle/* "$CRAFT_PART_INSTALL/"
    build-packages:
      - default-jdk-headless
      - libcurl4-openssl-dev
      - libgtk-3-dev
      - libpolkit-gobject-1-dev
      - libsecret-1-dev
      - lld-18
      - llvm-18
    stage-packages:
      - default-jre-headless
  polkit-locale:
    plugin: nil
    source: snap/meta/polkit/po
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/locale
      for po in *.po; do
        lang=${po%.po}
        mkdir -p $SNAPCRAFT_PART_INSTALL/usr/share/locale/$lang/LC_MESSAGES
        msgfmt $po -o $SNAPCRAFT_PART_INSTALL/usr/share/locale/$lang/LC_MESSAGES/app.openauthenticator.mo
      done
    build-packages:
      - gettext
  polkit-policy:
    plugin: dump
    source: snap/meta/polkit/polkit.app.openauthenticator.policy
    source-type: file
    organize:
      polkit.app.openauthenticator.policy: meta/polkit/polkit.app.openauthenticator.policy

plugs:
  polkit:
    action-prefix: app.openauthenticator
